name: CI

on:
  push:
    branches: [ "trunk" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "trunk" ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Zig Compiler
        uses: mlugg/setup-zig@v1.2.1
        with:
          version: "0.13.0"
          use-cache: true

      - name: Build library for Linux only
        if: matrix.os == 'ubuntu-latest'
        run: |
          # Build the library with headers and release mode on Linux only
          zig build-lib src/root.zig -lc -femit-h -Drelease-safe -target x86_64-linux-gnu
          
          # Move the generated header to the include directory
          mv root.h include/

          # Create the distribution directory
          mkdir -p dist

          # Copy the built library files and headers to the distribution
          cp libroot.a dist/
          cp include/zig.h dist/
          cp include/root.h dist/    # Include your generated header

      - name: Upload Release Binaries
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: zig-lib-binaries
          path: dist/
